In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('C:/Users/Admin/Learning_AI/daily-learning-AI/2026-10-10/train.csv', index_col="Id")
data.head()

    MSSubClass MSZoning  LotFrontage  LotArea  ... YrSold SaleType SaleCondition SalePrice
Id                                             ...
1           60       RL         65.0     8450  ...   2008       WD        Normal    208500
2           20       RL         80.0     9600  ...   2007       WD        Normal    181500
3           60       RL         68.0    11250  ...   2008       WD        Normal    223500
4           70       RL         60.0     9550  ...   2006       WD       Abnorml    140000
5           60       RL         84.0    14260  ...   2008       WD        Normal    250000

[5 rows x 80 columns]

In [5]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='str')

## Chọn những dữ liệu đặc trưng

In [6]:
feature = ["LotArea", "YearBuilt", "TotRmsAbvGrd", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr"]

## Splitting dataset into x and y

In [7]:
x = data[feature]
y = data["SalePrice"]
x.head()

    LotArea  YearBuilt  TotRmsAbvGrd  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr
Id
1      8450       2003             8       856       854         2             3
2      9600       1976             6      1262         0         2             3
3     11250       2001             6       920       866         2             3
4      9550       1915             7       961       756         1             3
5     14260       2000             9      1145      1053         2             4

In [8]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

## x, y -> x_train, y_train, x_test, y_test

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)

## Training model

In [10]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(random_state=1)

In [11]:
model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=1)

In [13]:
y_pred = model.predict(x_test.head())
y_pred

array([335000., 140200., 119000., 207500.,  85000.])

In [20]:
pd.DataFrame({'y': y_test.head(), 'y_pred': y_pred})

          y    y_pred
Id
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000   85000.0

In [21]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
model2 = RandomForestRegressor(random_state=1)
model2.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [28]:
model2_pred = model2.predict(x_test)
model2_pred[:5]

array([272420.        , 155031.        , 122411.5       , 188400.        ,
        90324.16666667])

In [29]:
x_test.head()

     LotArea  YearBuilt  TotRmsAbvGrd  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr
Id
530    32668       1957             9      2515         0         3             4
492     9490       1941             5       958       620         1             3
460     7015       1950             5       979       224         1             3
280    10005       1977             8      1156       866         2             4
656     1680       1971             6       525       567         1             3

In [34]:
model2.predict([[6000, 2026, 5, 1000, 2000, 3, 5]])

D:\Python\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([261192.49])